M48
; DRILL file {KiCad (6.0.0)} date Mon Jan 31 09:48:49 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-01-31T09:48:49+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X155.456Y-126.396
X155.456Y-132.176
T2
X192.048Y-96.012
X195.048Y-96.012
T0
M30
